/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:02:55 GMT 2019
 */

package org.ow2.proactive.catalog.service.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.service.exception.CatalogObjectNotFoundException;

public class CatalogObjectNotFoundException_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CatalogObjectNotFoundException catalogObjectNotFoundException0 = new CatalogObjectNotFoundException("");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CatalogObjectNotFoundException catalogObjectNotFoundException0 = new CatalogObjectNotFoundException();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CatalogObjectNotFoundException catalogObjectNotFoundException0 = new CatalogObjectNotFoundException("", "");
  }
}
