/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 15:01:37 GMT 2019
 */

package org.ow2.proactive.catalog.service.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.service.exception.CatalogObjectAlreadyExistingException;

public class CatalogObjectAlreadyExistingException_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CatalogObjectAlreadyExistingException catalogObjectAlreadyExistingException0 = new CatalogObjectAlreadyExistingException("sigz/RV8:@");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CatalogObjectAlreadyExistingException catalogObjectAlreadyExistingException0 = new CatalogObjectAlreadyExistingException((String) null, "sigz/RV8:@");
  }
}
