/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 16 14:48:14 GMT 2019
 */

package org.ow2.proactive.catalog.util.name.validator;

import org.junit.Test;
import static org.junit.Assert.*;
import org.ow2.proactive.catalog.util.name.validator.BucketNameValidator;

public class NameValidator_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BucketNameValidator bucketNameValidator0 = new BucketNameValidator();
      boolean boolean0 = bucketNameValidator0.isValid("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BucketNameValidator bucketNameValidator0 = new BucketNameValidator();
      // Undeclared exception!
      try { 
        bucketNameValidator0.isValid((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }
}
